apiVersion : apps/v1
kind: Deployment
metadata:
  name: dhiaelhakeangularappkubernetes 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhiaelhakeangularappkubernetes
  template:
    metadata:
      labels:
        app: dhiaelhakeangularappkubernetes 
    spec:
      containers:
        - name: dhiaelhakeangularappkubernetes 
          image: dhia001acr.azurecr.io/dhiaelhakeangularappkubernetes
          ports:
          - containerPort: 8